---
#products
product_name: The product name
version: The product version
variant: The product variant
allow_source_only: Bool
packages:
  package 1:
    arch:
    - arch1
    - arch2
    - and so on
    noarch:
    - arch1
    - arch2
    - and so on
    multilib:
    - arch1: arch2
    - arch3: aarch64
    - and so on
  package 2:
    arch:
    - arch1
    - arch2
    - and so on
    noarch:
    - arch1
    - arch2
    - and so on
    multilib:
    - arch1: arch2
    - arch3: aarch64
    - and so on
  and so on: